{{- if .Values.podDisruptionBudget.enabled }}
{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
{{- $component := dict "root" $ "name" $name "svc" $svc }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nlm-k2.componentName" $component }}
  labels:
    {{- include "nlm-k2.componentLabels" $component | nindent 4 }}
spec:
  maxUnavailable: {{ $.Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "nlm-k2.componentSelectorLabels" $component | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
